# Generated by Django 3.1.6 on 2023-07-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20230711_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='name',
            field=models.CharField(default='Ajsal K', max_length=255),
        ),
    ]
