# Generated by Django 3.1.6 on 2023-07-11 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20230711_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='designation',
            field=models.CharField(default='Software engineer', max_length=255),
        ),
    ]
