# Generated by Django 3.1.6 on 2023-07-12 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_testimonial_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='dob',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
