# Generated by Django 3.1.6 on 2023-07-12 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_student_studentgroup'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='web_student',
        ),
    ]
